AllCops:
  Include:
    - Gemfile
    - Rakefile
  Exclude:
    - vendor/**/*

RegexpLiteral:
  MaxSlashes: 1

UnusedMethodArgument:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/SignalException:
  Enabled: false

LineLength:
  Max: 180

MethodLength:
  Max: 60
 
Metrics/AbcSize:
  Max: 30

Style/DoubleNegation:
  Enabled: false

CyclomaticComplexity:
  Max: 12

Style/ClassAndModuleChildren:
  Enabled: false

Style/Blocks:
  Enabled: false

Style/TrailingComma:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/IndentHash:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/AlignParameters:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/GuardClause:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
