AllCops:
  Includes:
    - Gemfile
    - Rakefile
  Excludes:
    - vendor/**

RegexpLiteral:
  MaxSlashes: 1

UnusedMethodArgument:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/SignalException:
  Enabled: false

LineLength:
  Max: 160

MethodLength:
  Max: 60
 
Metrics/AbcSize:
  Max: 30

Style/DoubleNegation:
  Enabled: false

CyclomaticComplexity:
  Max: 12

Styles/ClassAndModuleChildren:
  Enabled: false

Style/Blocks:
  Enabled: false

Style/TrailingComma:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/IndentHash:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing
